<<<<<<< HEAD
db.url=jdbc:mysql://localhost:3306/meuplanner?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
=======
db.url=jdbc:mysql://localhost:3306/meuplanner?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
>>>>>>> 42c00c3b457271216264cad568f3551de49c20fb
db.user=root
db.password=
db.pool.maxSize=10
db.pool.minIdle=2
db.pool.connectionTimeoutMs=30000